apiVersion: v1
kind: Service
metadata:
  name: bush-service
spec:
  ports:
    - port: 9090
      targetPort: 9090
      appProtocol: tcp
  selector:
    app: bush
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bush-depolyment
spec:
  selector:
    matchLabels:
      app: bush
  replicas: 2
  template:
    metadata:
      labels:
        app: bush
        app.log.index: application
    spec:
      containers:
        - name: bush
          image: 676007236/bush:1.6.2
          env:
            - name: JAEAGER_COLLECTOR_ADDR
              value: jaeger-collector.istio-system.svc.cluster.local:14268
