apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidekiq-depolyment
spec:
  selector:
    matchLabels:
      app: sidekiq
  replicas: 2
  template:
    metadata:
      labels:
        app: sidekiq
        app.log.index: application
    spec:
      containers:
        - name: sidekiq
          image: 676007236/sidekiq-app:1.7
          env:
            - name: REDIS_HOST
              value: redis://redis-service.zhangwuh.svc.cluster.local:6379
