apiVersion: v1
kind: Service
metadata:
  name: sidekiq-service
spec:
  ports:
    - port: 6379
      name: redis
      targetPort: 6379
  selector:
    app: sidekiq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidekiq-depolyment
spec:
  selector:
    matchLabels:
      app: sidekiq
  replicas: 2
  template:
    metadata:
      labels:
        app: sidekiq
        app.log.index: application
    spec:
      containers:
        - name: redis
          image: bitnami/redis
          ports:
            - containerPort: 6379
              name: redis
              protocol: TCP
          env:
            - name: "ALLOW_EMPTY_PASSWORD"
              value: "yes"
        - name: sidekiq
          image: 676007236/sidekiq-app:latest
