apiVersion: v1
kind: Service
metadata:
  name: twoeyes-service
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: twoeyes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: twoeyes-depolyment
spec:
  selector:
    matchLabels:
      app: twoeyes
  replicas: 3
  template:
    metadata:
      labels:
        app: twoeyes
        app.log.index: application
    spec:
      containers:
        - name: twoeyes
          image: 676007236/twoeyes:1.6
          env:
            - name: REDIS_HOST
              value: redis://sidekiq-service.zhangwuh.svc.cluster.local:6379
            - name: PIDFILE
              value: ./server.pid
            - name: BUSH_SERVICE_ADDR
              value: bush-service.zhangwuh.svc.cluster.local
            - name: JAEAGER_COLLECTOR_ADDR
              value: http://jaeger-collector.istio-system.svc.cluster.local:14268
