---
# Permit co-located instances for solitary minikube virtual machines.

# Shrink default JVM heap.
esJavaOpts: "-Xmx1024m -Xms1024m"
replicas: 2
# Allocate smaller chunks of memory per pod.
resources:
  requests:
    cpu: "100m"
    memory: "2Gi"
  limits:
    cpu: "100m"
    memory: "2Gi"

# Request smaller persistent volumes.
volumeClaimTemplate:
  storageClassName: gp2
  resources:
    requests:
      storage: 1Gi

readinessProbe:
   failureThreshold: 3
   initialDelaySeconds: 10
   periodSeconds: 10
   successThreshold: 3
   timeoutSeconds: 5

clusterHealthCheckParams: "wait_for_status=green"
